redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/zunixe/Documents/ScanOrder/web"
publishOrigin = "config"
base = "/Users/zunixe/Documents/ScanOrder/web"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/privacy-policy"
to = "/privacy-policy.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/account-delete"
to = "/account-delete.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]