default_platform(:android)

platform :android do
  desc "Upload existing AAB to Google Play production"
  lane :upload do
    upload_to_play_store(
      track: "production",
      aab: "build/app/outputs/bundle/release/app-release.aab",
      release_status: "completed",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

  desc "Upload to internal testing"
  lane :upload_internal do
    upload_to_play_store(
      track: "internal",
      aab: "build/app/outputs/bundle/release/app-release.aab",
      release_status: "draft",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end
